spring:
  datasource:
   url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
   username: hr
   password: hr
  jpa:
    show-sql: true
  application:    name: camp-service
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    shutdown:
      enabled: true
 
info:
   build:
     artifactId: '@project.artifactId@'
     groupId: '@project.groupId@'
   java:
     version: 8.0  
server:
  port: 2020
  
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
  